### ISSUE TITLE
Error when no $pluginKey given to LegalTextHandler::__construct()

### ISSUE THREAD

**Issue by joshsedl** [eRecht24/rechtstexte-sdk#1]
When passing no third ($pluginKey) parameter to
`new LegalTextHandler($apiKey, $pushType);`

this leads to the following follow-up error:

> TypeError: Argument 2 passed to eRecht24\RechtstexteSDK\Service\EndpointService::__construct() must be of the type string, null given, called in /var/www/html/vendor/erecht24/rechtstexte-sdk/src/RechtstexteSDK/ApiHandler.php on line 48 in eRecht24\RechtstexteSDK\Service\EndpointService->__construct() (line 105 of /var/www/html/vendor/erecht24/rechtstexte-sdk/src/RechtstexteSDK/Service/EndpointService.php).

**Proposed resolution:**
Make $pluginKey parameter required in 
`public function __construct(string $apiKey, string $documentType, ?string $pluginKey = null)`

**Comment by etlam** [comment]
Thanks, I changed the docs and prevented the PHP TypeError. The plugin key is needed and is only optional as we pass it for our Unit Tests as environment variable.  
I think it might be easier to use the `ApiHandler` to interact with the legal texts.
